imports:
- path: ../templates/master-db.jinja
  name: master-db.jinja
- path: ../templates/replicas.jinja
  name: replicas.jinja
- path: ../templates/user.jinja
  name: user.jinja

resources:
- name: kunipon-master-db
  type: master-db.jinja
  properties:
    tier: db-f1-micro
    dataDiskSizeGb: 10
    autoResize: true
    autoResizeLimit: 100
    buckupEnables: true
    buckupStartTime: 00:00
    failover: true
    readReplicas: 1
- name: kunipon-replicas
  type: replicas.jinja
    masterTier: db-f1-micro
    readReplicaTier: db-f1-micro
    failover: true
    readreplicas: 1
- name: kunipon-db-user
  type: user.jinja
  properties:
    rootUserPassword: root-password
    dbReadWriteUserName: kunipon
